### ISSUE TITLE
Dependency issue

### ISSUE THREAD

**Issue by murari-kumar** [dogecoin/libdohj#12]
<dependency>
            <groupId>org.bitcoinj</groupId>
            <artifactId>bitcoinj-core</artifactId>
            <version>0.14-SNAPSHOT</version>
        </dependency> 

the above dependency is used in this api. when i am using this api for developing litecoin application then  in my application unable to download this dependency. I am getting a error during maven install i.e
Failed to execute goal on project example: Could not resolve dependencies for project " "Litecoin:example:jar:0.0.1-SNAPSHOT: Could not find artifact org.bitcoinj:bitcoinj-core:jar:0.14-SNAPSHOT -> [Help 1]". How can i fix it this error

**Comment by rnicoll** [comment]
libdohj uses a version of bitcoinj which has not been released yet, so you'll need to manually install the artifact. Clone the repository https://github.com/bitcoinj/bitcoinj and run "mvn install" from within it to install the master branch, which should resolve this.
